### ISSUE TITLE
Trouble launching Jupyter Notebook after Cheyenne udpdate

### ISSUE THREAD

**Issue by edougherty32** [NCAR/NCAR-pangeo-tutorial#19]
Hi all, forgive me if this isn't the correct place for this issue, but I am having an issue launching Jupyter notebook in the pangeo environment after the Cheyenne upgrade. 

I follow instructions [here](http://pangeo.io/setup_guides/hpc.html) to launch the notebook, and when I enter: 

`jupyter lab --no-browser --ip=`hostname` --port=8877`

I receive the following error:

```
Traceback (most recent call last):
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/notebook/notebookapp.py", line 1627, in initialize
    self.init_configurables()
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/notebook/notebookapp.py", line 1317, in init_configurables
    connection_dir=self.runtime_dir,
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/glade/u/home/doughert/miniconda3/envs/pangeo/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/user/24367'
```

I have never had issues with this before, which is why I think this is related to the Cheyenne upgrade. Does anyone have ideas about how to fix this? Thanks in advance.

**Comment by andersy005** [comment]
@edougherty32, 

I am not sure what the issue is because I am able to launch jupyter lab:

```bash
abanihi@cheyenne2: ~ $ jupyter lab --no-browser --ip=`hostname` --port=8877
[I 09:27:59.985 LabApp] JupyterLab extension loaded from /glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/jupyterlab
[I 09:27:59.986 LabApp] JupyterLab application directory is /glade/work/abanihi/softwares/miniconda3/envs/analysis/share/jupyter/lab
[W 09:28:01.612 LabApp] JupyterLab server extension not enabled, manually loading...
[I 09:28:01.628 LabApp] JupyterLab extension loaded from /glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/jupyterlab
[I 09:28:01.628 LabApp] JupyterLab application directory is /glade/work/abanihi/softwares/miniconda3/envs/analysis/share/jupyter/lab
[I 09:28:01.629 LabApp] Serving notebooks from local directory: /glade/u/home/abanihi
```

- Which directory are you in when you launch the jupyter server?
- What is the output of `echo $XDG_RUNTIME_DIR`?

**Comment by edougherty32** [comment]
@andersy005–I launch it from my work directory (/glade/work/doughert), which has always worked for me before. 

The output of `echo $XDG_RUNTIME_DIR` is 
`/run/user/24367`

**Comment by andersy005** [comment]
Can you check for the owner of `/run/user/24367` directory with 

```bash
ls -l /run/user/24367
```

**Comment by edougherty32** [comment]
@andersy005 – I tried that but received the following error message: 

`ls: cannot access '/run/user/24367': No such file or directory`

So I'm not sure what is going on here.

**Comment by kmpaul** [comment]
This should be reported to CISL Help.  It is most certainly a consequence of the Cheyenne upgrades and they should be notified of the issue.

**Comment by andersy005** [comment]
It appears that the `$XDG_RUNTIME_DIR` doesn't exist yet (probably once cheyenne is fully operational again, the issue may go away). For the time being, you may want to unset the `XDG_RUNTIME_DIR`:

`unset XDG_RUNTIME_DIR` and launch jupyter again

**Comment by edougherty32** [comment]
Thanks @andersy005 – that did the trick. 

@kmpaul – I'll notify CISL help as you suggested, because I'm sure I'm not the only one with this issue.

**Comment by davidedelvento** [comment]
I am not able to reproduce this issue and I am working with the user about it.

FWIW, start-jupyter works fine for CISL-supported python's as described at https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/software/python
